### ISSUE TITLE
site config 설정하기

### ISSUE THREAD

**Issue by secret-papa** [secret-papa/blog#2]
starter에 있는 config 설정을 알맞게 수정한다.

**Comment by secret-papa** [comment]
간단하게 변경할 수 있는 config만 변경했으며, 이후에 어떤 값들을 넣어야 되는지 정해지면 이후에 다시 작업한다.

**Comment by ldsys** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](http://darksouls2.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](http://darksouls2.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
bemodestdoteth, @Hoalab19, @tranphuong92, @Casa6666, @Munabrown, @K46E, @kaikwon5, @ereynier, @edashk1, @rwbaumg, @iq5001, @0xdrio, @mparoni55, @porterkaufman0, @Athym, @super117893344p, @smile0134, @Motrading, @blackboy2p2, @Aartilan, @owlinstack, @NFTsupreme, @billybudz, @Findisland, @Lexiflexit, @eltpadnd123, @alphayk07, @weekendul, @bakgwei, @Imranakk, @Masaphy, @naveensoman, @a104995, @stopgogo, @0xbei, @Duhkha-dev, @Feidie8848, @HelenaVolskaia, @built1Protocol, @kalluk, @geragol772, @innocent42, @Erjanite, @silviofaria, @dreamsnotion, @aminah-io, @dani29051980, @masabb, @BoNneDX, @rizvanhaider
